services:
  - type: web
    name: teacher-recruitment
    env: python
    plan: free
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
